quarkus:

  datasource:
    db-kind: mysql
    reactive:
      url: mysql://localhost:3306/orderdb
    username: root
    password: admin
  hibernate-orm:
    database-generation:
      drop-and-create: true
    log:
      sql: true
  hibernate-reactive:
    database-generation:
      drop-and-create: true
  package:
    jar:
      enabled: true
    test-port: 0
kafka:
  bootstrap:
    servers: PLAINTEXT://192.168.1.48:19092
mp:
  messaging:
    connector:
      smallrye-kafka:
        schema:
          registry:
            url: http://192.168.1.48:8081
        auto:
          register:
            schemas: false
        use:
          latest:
            version: true

    outgoing: ## va salir del microservicio para que vaya al topico de kafka
      order-emitter:
        connector: smallrye-kafka
        topic: order-topic